#include "wise_enum.h"
#include <string_view>

using namespace std::string_view_literals;

WISE_ENUM(
    MyEnum, (ALKDSJSALDKJFALSKFJLKJLKJSDF1, 1),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF10, 10), (ALKDSJSALDKJFALSKFJLKJLKJSDF11, 11),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF12, 12), (ALKDSJSALDKJFALSKFJLKJLKJSDF13, 13),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF14, 14), (ALKDSJSALDKJFALSKFJLKJLKJSDF15, 15),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF16, 16), (ALKDSJSALDKJFALSKFJLKJLKJSDF17, 17),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF18, 18), (ALKDSJSALDKJFALSKFJLKJLKJSDF19, 19),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF110, 20),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF111, 21),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF112, 22),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF113, 23),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF114, 24),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF115, 25),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF116, 26),
    (ALKDSJSALDKJFALSKFJLKJLKJSDF217, 27))

// constexpr auto foo1(const char *input) {
//   auto my_enum = wise_enum::from_string<MyEnum>(input);
//   return wise_enum::to_string(*my_enum);
// }

void foo1(std::string_view input);

void foo2(MyEnum me) { foo1(wise_enum::to_string(me)); }
